
name: PDF Converter CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image
      run: docker build . --file SampleApp/Catalog/Dockerfile --tag hasitha2kandy/html-to-pdf-converter:${{env.version}}

    - name: Tag the Latest image
      run: docker tag hasitha2kandy/html-to-pdf-converter:${{env.version}} hasitha2kandy/html-to-pdf-converter:latest
      
    - name: Push images to Docker Hub
      run: |
        docker push hasitha2kandy/html-to-pdf-converter:${{env.version}}
        docker push hasitha2kandy/html-to-pdf-converter:latest
